### PR TITLE
Adding Abut us page

### PR DESCRIPTION
**Pull request by vishalverma9572**
Pull Request: Adding About Us page in About folder
this fixes SyedImtiyaz-1/Code-Shop #71 

Description:
I have added About.html, About.css, About.js and image folde
I have also linked this page to index.html
these are the images
About Us _ Hot Gadgets_page-0001
About Us _ Hot Gadgets_page-0002
About Us _ Hot Gadgets_page-0003
About Us _ Hot Gadgets_page-0004

About Us _ Hot Gadgets_page-0005
This page is Completely Responsive

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
please resolve conflicts

**Comment by vishalverma9572** [comment]
I have resolved this please check it and let me now

**Comment by vishalverma9572** [comment]
I have resolved the conflicts. please check it and let me know...

**Comment by vishalverma9572** [comment]
Please check it and update me Sir..

**Comment by vishalverma9572** [comment]
Sir,Please add hactoberfest-accepted label in this PR

**Pull request merged**
